# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server/party.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12server/party.proto\x12\x08tutorial\"E\n\x05Party\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x0f\n\x07tickets\x18\x03 \x01(\x05\x12\x0f\n\x07\x61rtists\x18\x04 \x03(\t\"-\n\x0cPartyRequest\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x0f\n\x07tickets\x18\x02 \x01(\x05\x32M\n\x0cPartyService\x12=\n\x10SubscribeToParty\x12\x16.tutorial.PartyRequest\x1a\x0f.tutorial.Party0\x01\x42\x16\n\x08sr.protoB\nPartyProtob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server.party_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\010sr.protoB\nPartyProto'
  _PARTY._serialized_start=32
  _PARTY._serialized_end=101
  _PARTYREQUEST._serialized_start=103
  _PARTYREQUEST._serialized_end=148
  _PARTYSERVICE._serialized_start=150
  _PARTYSERVICE._serialized_end=227
# @@protoc_insertion_point(module_scope)
