# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import party_pb2 as server_dot_party__pb2


class PartyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeToParty = channel.unary_stream(
                '/tutorial.PartyService/SubscribeToParty',
                request_serializer=server_dot_party__pb2.PartyRequest.SerializeToString,
                response_deserializer=server_dot_party__pb2.Party.FromString,
                )


class PartyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubscribeToParty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PartyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeToParty': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToParty,
                    request_deserializer=server_dot_party__pb2.PartyRequest.FromString,
                    response_serializer=server_dot_party__pb2.Party.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tutorial.PartyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PartyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribeToParty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/tutorial.PartyService/SubscribeToParty',
            server_dot_party__pb2.PartyRequest.SerializeToString,
            server_dot_party__pb2.Party.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
